import CardProduct from "./CardProduct";
import images from "../assets/images/product.png";

const ListaProducts = [
  {
    id: 1,
    title: "Produto 1",
    price: "199.99",
    newprice: "1.99",
    image: "tenis.jpg",
    description: "Produto",
  },
  {
    id: 2,
    title: "Produto 2",
    price: "199.99",
    newprice: "1.99",
    image: "tenis.jpg",
    description: "Produto",
  },
  {
    id: 3,
    title: "Produto 3",
    price: "199.99",
    newprice: "1.99",
    image: "tenis.jpg",
    description: "Produto",
  },
  {
    id: 4,
    title: "Produto 4",
    taxaEntrega: "5.00",
    price: "199.99",
    newprice: "1.99",
    image: "tenis.jpg",
    description: "Produto",
  },
  {
    id: 5,
    title: "Produto 5",
    taxaEntrega: "5.00",
    price: "199.99",
    newprice: "1.99",
    image: "tenis.jpg",
    description: "Produto",
  },
  {
    id: 6,
    title: "Produto 6",
    taxaEntrega: "5.00",
    price: "199.99",
    newprice: "1.99",
    image: "tenis.jpg",
    description: "Produto",
  },
  {
    id: 7,
    title: "Produto 7",
    taxaEntrega: "5.00",
    price: "199.99",
    newprice: "1.99",
    image: "tenis.jpg",
    description: "Produto",
  },
  {
    id: 8,
    title: "Produto 8",
    taxaEntrega: "5.00",
    price: "199.99",
    newprice: "1.99",
    image: "tenis.jpg",
    description: "Produto",
  },
  {
    id: 9,
    title: "X-Frango",
    taxaEntrega: "5.00",
    price: "8.00",
  },
  {
    id: 9,
    title: "X-Frango",
    taxaEntrega: "5.00",
    price: "8.00",
  },
  {
    id: 10,
    title: "X-Salada",
    taxaEntrega: "5.00",
    price: "8.00",
  },
  {
    id: 11,
    title: "X-Bacon",
    taxaEntrega: "5.00",
    price: "8.00",
  },
  {
    id: 12,
    title: "Hambuguer",
    taxaEntrega: "5.00",
    price: "R$6.00",
  },
];

export default ListaProducts;
